language: cpp
sudo: false
compiler:
- gcc
before_install:
- source <(curl -SLs https://raw.githubusercontent.com/A2-Collaboration/travis-container-packets/gcc/setup.sh)
- source <(curl -SLs https://raw.githubusercontent.com/A2-Collaboration/travis-container-packets/cmake/setup.sh)
script: "./build_APLCON.sh"
os:
- linux
deploy:
  provider: releases
  api_key:
    secure: Sn01rg53kGdiWxaZRdbR8IbtTs2EhIkYDQlx7etmEdEm7vecjwyN5aFWy006UywcPJwTGToqnQ+FUvtK6ri2vzG/vowhPrSnUmHkcjYwoRqEjxRIm1hUaWkEFFj3BAxVEhoOr5z5zoJXnlUApJy/qr+QAc8P4rW1mTiJJNTKHsoiar1EgwOkBS3rA5ar0B3tEwUvKlU6TzeuLO8qJEI+T3akoCyloonQQ3Klhr9mfMk0ImmK74FEXMj3pYQet1SUusC86LlKNDOZiwXeT16ZY59odNPZDajouqXAD83lpRCCRPc2lkEj7lap3/SRr5c7uhTnGqjo1oJTZJuozoMpLUFDaKlUdppPMCGsdnHo2C1w12Bf+NqvU7V/GCLfoqqizQyPBRjiTy8tvLcnO3Jniw+Gj5EzC092byOtowJ/VqpnOhzz+IvCoaoLLOUo25VMJpqCGSZmBk9kKhYd2uTOXTyDqixH8DXU4pvbiWwTpD8NgHwyyA+vwN+Nvo1DSmSqz7m56QkudGf9xQ9VkzcXokOe0LMQ+Ipw5WM8mpN3iSGnPrOkfUgUhb5+UHpoIDtBBH2cbMYgEurVDI+te2XNvfbfhE68vfg04ev/5pgjGQexFkyC2lnXgTCGt4J0WDiLw7Meggl4wovG3A4+/kBqQRuQnCmgkw/xAbADo27kbhg=
  file: APLCON.tar.bz2
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
