language: cpp
sudo: false
compiler:
  - gcc
before_install:
  # Get GCC 4.9.2
  - if [ "$CXX" == "g++" ]; then wget https://github.com/A2-Collaboration-dev/travis-container-packets/releases/download/gcc-4.9.2/gcc.tar.bz2; fi
  - if [ "$CXX" == "g++" ]; then tar -xjf gcc.tar.bz2; fi
  - if [ "$CXX" == "g++" ]; then rm gcc.tar.bz2; fi
  - if [ "$CXX" == "g++" ]; then export PATH=$(pwd)/gcc/bin:$PATH; fi
  - if [ "$CXX" == "g++" ]; then export LIBRARY_PATH=$(pwd)/gcc/lib64:$LIBRARY_PATH; fi
  - if [ "$CXX" == "g++" ]; then export LD_LIBRARY_PATH=$(pwd)/gcc/lib64:$LD_LIBRARY_PATH; fi
  - if [ "$CXX" == "g++" ]; then export CPLUS_INCLUDE_PATH=$(pwd)/gcc/include/c++/4.9.2:$CPLUS_INCLUDE_PATH; fi
script: "./build_aplcon.sh"
os:
  - linux
