language: cpp
sudo: false
compiler:
  - gcc
before_install:
  # Get GCC 4.9.2
  - source <(curl -SLs https://raw.githubusercontent.com/A2-Collaboration-dev/travis-container-packets/gcc/setup.sh)
  # Get CMake 3.1
  - source <(curl -SLs https://raw.githubusercontent.com/A2-Collaboration-dev/travis-container-packets/cmake/setup.sh)
script: "./build_APLCON.sh"
os:
  - linux
