language: cpp
sudo: false
compiler:
- gcc
before_install:
- source <(curl -SLs https://raw.githubusercontent.com/A2-Collaboration-dev/travis-container-packets/gcc/setup.sh)
- source <(curl -SLs https://raw.githubusercontent.com/A2-Collaboration-dev/travis-container-packets/cern-root/setup.sh)
script: "./build_gsi-pluto.sh"
os:
- linux
